### ISSUE TITLE
"Could not find a JavaScript runtime" error during build

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/flatpak.github.io#468]
Build fails on:

```
/usr/share/gems/gems/execjs-2.8.1/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /usr/share/gems/gems/execjs-2.8.1/lib/execjs.rb:5:in `<module:ExecJS>'
	from /usr/share/gems/gems/execjs-2.8.1/lib/execjs.rb:4:in `<top (required)>'
	from /usr/share/gems/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `require'
	from /usr/share/gems/gems/coffee-script-2.4.1/lib/coffee_script.rb:1:in `<top (required)>'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/renderers/coffee_script.rb:2:in `require'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/renderers/coffee_script.rb:2:in `<top (required)>'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/rendering.rb:34:in `require'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/rendering.rb:34:in `registered'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/extensions.rb:78:in `register'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:175:in `<class:Application>'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:24:in `<module:Middleman>'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/application.rb:23:in `<top (required)>'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:95:in `require'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:95:in `shared_instance'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli/build.rb:62:in `build'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/command.rb:29:in `run'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/command.rb:135:in `run'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /usr/share/gems/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
	from /usr/share/gems/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
	from /usr/bin/middleman:23:in `load'
	from /usr/bin/middleman:23:in `<main>'
```

See for example: https://github.com/flatpak/flatpak.github.io/runs/2683305609 or https://github.com/flatpak/flatpak.github.io/runs/2720383816

/cc @barthalion

**Comment by AsciiWolf** [comment]
@barthalion Were you able to look at this issue?

**Comment by AsciiWolf** [comment]
Still the same problem with latest commit: https://github.com/flatpak/flatpak.github.io/runs/3098061310

**Comment by barthalion** [comment]
I remember, I'm just short on time till the middle of August.

**Comment by AsciiWolf** [comment]
Any news regarding this issue? Site deployment is broken since March because of this.
