### ISSUE TITLE
Building this

### ISSUE THREAD

**Issue by razzeee** [flatpak/flatpak.github.io#506]
I'm having problems building this, I'm not sure if the instructions are still enough.

I've tried to set it up in a docker container of fedora 30
But it fails with 

```
[root@54f3599d7266 flatpak.github.io]# bundle install
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
The git source `git://github.com/barthalion/middleman-matomo.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Using i18n 0.7.0
Using minitest 5.14.4
Using thread_safe 0.3.6
Using tzinfo 1.2.9
Using activesupport 4.2.11.3
Using execjs 2.8.1
Using autoprefixer-rails 10.3.3.0
Using ffi 1.15.4
Using sassc 2.4.0
Using bootstrap-sass 3.4.1
Using bundler 1.17.2
Using mime-types-data 3.2021.1115
Using mime-types 3.4.1
Using mini_portile2 2.6.1
Using racc 1.6.0
Using nokogiri 1.12.5 (x86_64-linux)
Using rack 1.6.13
Using rack-test 1.1.0
Using xpath 2.1.0
Using capybara 2.4.4
Using chunky_png 1.4.0
Using coffee-script-source 1.12.2
Using coffee-script 2.4.1
Using multi_json 1.15.0
Using sass 3.4.25
Using compass-core 1.0.3
Using compass-import-once 1.0.5
Using rb-fsevent 0.11.0
Using rb-inotify 0.10.1
Using compass 1.0.3
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using erubis 2.7.0
Using temple 0.8.2
Using tilt 1.4.1
Using haml 5.2.2
Using hike 1.2.3
Using uber 0.0.15
Using hooks 0.4.1
Using json 2.6.1
Using kramdown 1.17.0
Using libv8-node 15.14.0.1 (x86_64-linux)
Using listen 3.0.8
Using padrino-support 0.12.9
Using padrino-helpers 0.12.9
Using thor 1.1.0
Using middleman-core 3.4.1
Using middleman-more 3.1.6
Using sprockets 2.12.5
Using sprockets-helpers 1.0.1
Using sprockets-sass 1.0.3
Using middleman-sprockets 3.1.4
Using uglifier 2.7.2
Using middleman 3.4.1
Using net-ssh 6.1.0
Using net-sftp 3.0.0
Using ptools 1.4.2
Using middleman-deploy 1.0.0
Using rack-livereload 0.3.17
Using middleman-livereload 3.4.7
Using middleman-matomo 0.0.1 from git://github.com/barthalion/middleman-matomo.git (at master@62f213a)
Using mini_racer 0.4.0
Using redcarpet 3.5.1
Bundle complete! 12 Gemfile dependencies, 64 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
[root@54f3599d7266 flatpak.github.io]# bundle exec middleman server
Deprecation warning: Expected string default value for '--instrument'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
Deprecation warning: Expected string default value for '--reload-paths'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
Deprecation warning: Expected string default value for '--instrument'; got false (boolean).
This will be rejected in the future unless you explicitly pass the options `check_default_type: false` or call `allow_incompatible_default_type!` in your code
You can silence deprecations warning by setting the environment variable THOR_SILENCE_DEPRECATION.
== The Middleman is loading
== LiveReload accepting connections from ws://172.17.0.2:35729
bundler: failed to load command: middleman (/usr/bin/middleman)
NoMethodError: undefined method `files' for Middleman::Application::MiddlemanApplication1:Class
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/configuration.rb:37:in `method_missing'
  /usr/share/gems/gems/middleman-livereload-3.4.7/lib/middleman-livereload/extension_3_1.rb:48:in `block in initialize'
  /usr/share/gems/gems/uber-0.0.15/lib/uber/options.rb:96:in `instance_exec'
  /usr/share/gems/gems/uber-0.0.15/lib/uber/options.rb:96:in `proc!'
  /usr/share/gems/gems/uber-0.0.15/lib/uber/options.rb:82:in `evaluate_for'
  /usr/share/gems/gems/uber-0.0.15/lib/uber/options.rb:60:in `call'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/hook.rb:59:in `evaluate_callback'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/hook.rb:55:in `execute_callback'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/hook.rb:40:in `block in run'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `each'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `inject'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/hook.rb:39:in `run'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks.rb:55:in `run_hook_for'
  /usr/share/gems/gems/hooks-0.4.1/lib/hooks/instance_hooks.rb:6:in `run_hook'
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/core_extensions/request.rb:57:in `inst'
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:132:in `new_app'
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/preview_server.rb:31:in `start'
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli/server.rb:89:in `server'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/gems/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:72:in `method_missing'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/command.rb:29:in `run'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/command.rb:135:in `run'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/gems/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
  /usr/share/gems/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
  /usr/share/gems/gems/middleman-core-3.4.1/lib/middleman-core/cli.rb:20:in `start'
  /usr/share/gems/gems/middleman-core-3.4.1/bin/middleman:18:in `<top (required)>'
  /usr/bin/middleman:23:in `load'
  /usr/bin/middleman:23:in `<top (required)>'

```

So I would  be interested, if this still works for anyone else :/

**Comment by razzeee** [comment]
Cloing due to there now being a working devcontainer
